### ISSUE TITLE
avrdude: Error: Could not find USBtiny device (0x1781/0xc9f)

### ISSUE THREAD

**Issue by datomnurdin** [josanastrid/gemma-codelab#1]
I trying to upload my code into gemma but not successful because I got this kind of error message.

```
avrdude: Error: Could not find USBtiny device (0x1781/0xc9f)
```

Please advice. Thank you.

P.S: I'm using OSX 10.11.1 #WomenTechMaker

**Comment by ImanolGo** [comment]
Same problem here. Did anyone find a solution?

**Comment by ImanolGo** [comment]
I found a solution that worked for me:

By connecting Gemma through a USB 2.0 Hub it connects properly.

I hope it helps.

**Comment by josanastrid** [comment]
Thank you, @ImanolGo. @datomnurdin Yes, connecting Gemma through a USB 2.0 hub works. I just don't really get it because with Air and 15" pro with the same OSX version, it works perfectly. And even before, it worked with my 13" pro but stopped working suddenly. Connected the Gemma with USB 2.0 and it worked again. Until now, I'm still figuring why this is happening.
